{% set name = "pytest-replay" %}
{% set version = "0.2.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7c08cba713c9335f2149f0ef9587b92467d60365d10546837a1952042377601d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - pip
    - setuptools_scm
  run:
    - pytest >=3.0.0

test:
  imports:
    - pytest_replay

about:
  home: https://github.com/ESSS/pytest-replay
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: Saves shell scripts that allow re-execute previous pytest runs to reproduce crashes or flaky tests
  description: "Saves shell scripts that allow re-execute previous pytest runs to reproduce crashes or flaky tests"
  dev_url: https://github.com/ESSS/pytest-replay

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
    - prusse-martin
