travis:
  secure:
    BINSTAR_TOKEN: T0Z1tJCZ+Dvze5GliW300QvD7K3DPZgFsqOXSqemVhva2vSKJqFIYoY3KW/VGFLQOAUnKbwQvJvUryGSaDI+MOF3odYrl9en/rweNzle+a2zPq04j2mwGORfKmWD49L4YLaItW7ZrE7V2WoZNR5l7olao/PZzBugpqUC+y9QjV2nsSFD3Ei3Cj3978F5OyhJRFQ67rAygsmjpZAWe000UxTx4is23ZYOQUTvL19x9z2p4d3zl/os7k4PCr1jW9aL44c/5wYHbx58M6kHwQEveYIaA8J9jdvUObeCvtMoIsEFqJ2eM43A2Zf4ok0zqQTb3GlahPWF9ymPmsDvUjEaceYJhbANCJrOxEtFb0MGMZNxQj8SaHUyRDxoiwLLaKpZzun9zJrzHIdj9I/dmJ28CW7WL16TH1IXmEFin3L14COyty9Wb/z2cNCwtisdAN7GWzCvUPCc9PCJpoYONsT1HMdjX38s3xUcgmS/gvvl51bd24vLc3iJN20u7hcqtCn9oCTlCvAehSATBuIFmyeIJsgJD+W/10PvsMfK9LzeU5K/LHJru/X6IgQajEx+KeC/3TmIogiqxsy4jO0uJnHn8F7UZwRA/tPdXCwqksF20kbZXClwMshJe20+7TnxkeOBdfN6rSsiQ5gGJvtUKQTCz/nwkPXX03q8K0FOQjpkgX0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
